services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/src
    command: poetry run python -m app.main

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
