services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
    command: poetry run python app/main.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
